# Generated by Django 2.2.17 on 2020-12-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_customtext_hfhgf"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hgfjgjh",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hgfhgfgh", models.BigIntegerField()),
            ],
        ),
    ]
