# Generated by Django 2.2.17 on 2020-12-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_hgfjgjh"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="jhgjhgjhg",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
