# Generated by Django 2.2.17 on 2020-12-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_auto_20201218_0645"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customtext",
            old_name="hfhgf",
            new_name="b1",
        ),
        migrations.RenameField(
            model_name="customtext",
            old_name="title",
            new_name="c1",
        ),
    ]
