# Generated by Django 2.2.17 on 2020-12-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20201218_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='hgfghfhfghf',
            new_name='jhgjhg',
        ),
    ]
